<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <RootNamespace>Screenstop.Capture</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Screenstop.Core\Screenstop.Core.csproj" />
  </ItemGroup>

</Project>
