<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Screendrop.Rendering</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="2.88.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Screendrop.Core\Screendrop.Core.csproj" />
  </ItemGroup>

</Project>
